######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 23 16:12:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QList
SOURCES += my_QList.cpp
