######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 23 11:52:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
FORMS += dialog.ui
SOURCES += dialog.cpp main.cpp
QT += network
