######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 21 20:24:57 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
