######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 23 15:38:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += my_QVector.cpp
